{
 "title": "Cryptos",
 "description": "Cryptomonedas graficos",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "BTC Precio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_precio_actual{par=\"BTCUSDT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH Precio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_precio_actual{par=\"ETHUSDT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evolución precio BTC / ETH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "crypto_precio_actual", "legendFormat": "{{par}}" }
   ]
  },
  {
   "title": "Mensajes desde Binance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(binance_mensajes_total[1m])",
     "legendFormat": "{{par}}"
    }
   ]
  },
  {
   "title": "Mensajes publicados en Kafka",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "rate(kafka_mensajes_publicados_total[1m])",
     "legendFormat": "{{par}}"
    }
   ]
  }
 ]
}